from lemminflect import getInflection


def get_verb_forms(word):
    """Returns V1-V4 forms: base, past simple, past participle, -ing (gerund)."""
    v2 = getInflection(word, tag='VBD')
    v3 = getInflection(word, tag='VBN')
    v4 = getInflection(word, tag='VBG')
    return {
        "v1": word,
        "v2": v2[0] if v2 else word,
        "v3": v3[0] if v3 else word,
        "v4": v4[0] if v4 else word
    }


def get_adjective_forms(word):
    """
    Returns comparative/superlative forms, but ONLY if they're forms that have
    actually been observed in real usage (inflect_oov=False) — not ones
    artificially generated by generic suffix rules. This avoids nonsense like
    "goer"/"goest" for rare adjective senses (e.g. "go" meaning "ready") that
    aren't genuinely used in comparative form.
    """
    comp = getInflection(word, tag='JJR', inflect_oov=False)
    sup = getInflection(word, tag='JJS', inflect_oov=False)
    return {
        "comparative": comp[0] if comp else None,
        "superlative": sup[0] if sup else None
    }